classDiagram
class TimerUnitSqlite
TimerUnitSqlite : +db Database
TimerUnitSqlite o-- Database
TimerUnitSqlite : -_table$ String
TimerUnitSqlite : +validFields List~String~
TimerUnitSqlite : +saveSnapshot() dynamic
TimerUnitSqlite : +queryByUuid() dynamic
TimerUnitSqlite : +queryByField() dynamic
TimerUnitSqlite : +deleteByField() dynamic
SnapshotRepository <|-- TimerUnitSqlite

class SettingsSqlite
SettingsSqlite : +db Database
SettingsSqlite o-- Database
SettingsSqlite : -_table$ String
SettingsSqlite : +validFields List~String~
SettingsSqlite : +saveSnapshot() dynamic
SettingsSqlite : +queryByUuid() dynamic
SnapshotRepository <|-- SettingsSqlite

class SnapshotRepository
<<abstract>> SnapshotRepository
SnapshotRepository : +validFields List~String~
SnapshotRepository : +saveSnapshot()* dynamic
SnapshotRepository : +queryByUuid()* dynamic
SnapshotRepository : +isValidField() bool

class TaskSqlite
TaskSqlite : +db Database
TaskSqlite o-- Database
TaskSqlite : -_table$ String
TaskSqlite : +validFields List~String~
TaskSqlite : +saveSnapshot() dynamic
TaskSqlite : +queryByUuid() dynamic
TaskSqlite : +deleteByField() dynamic
TaskSqlite : +updateByField() dynamic
TaskSqlite : +queryBatchByField() dynamic
TaskSqlite : +queryByField() dynamic
TaskSqlite : +queryBatchByFieldBefore() dynamic
TaskSqlite : +queryBatchByFieldAfter() dynamic
TaskSqlite : +getExtremeByField() dynamic
TaskSqlite : +howMany() dynamic
TaskSqlite : +reorderAll() dynamic
TaskSqlite : +reorderAround() dynamic
SnapshotRepository <|-- TaskSqlite

class TaskMetaSqlite
TaskMetaSqlite : +db Database
TaskMetaSqlite o-- Database
TaskMetaSqlite : -_table$ String
TaskMetaSqlite : +validFields List~String~
TaskMetaSqlite : +saveSnapshot() dynamic
TaskMetaSqlite : +queryByUuid() dynamic
TaskMetaSqlite : +queryByField() dynamic
TaskMetaSqlite : +deleteByField() dynamic
SnapshotRepository <|-- TaskMetaSqlite

class TaskMappingSqlite
TaskMappingSqlite : +db Database
TaskMappingSqlite o-- Database
TaskMappingSqlite : -_table$ String
TaskMappingSqlite : +validFields List~String~
TaskMappingSqlite : +saveSnapshot() dynamic
TaskMappingSqlite : +queryByUuid() dynamic
TaskMappingSqlite : +queryByField() dynamic
TaskMappingSqlite : +loadMappingsForTask() dynamic
TaskMappingSqlite : +loadMappingsForEntity() dynamic
TaskMappingSqlite : +deleteMapping() dynamic
TaskMappingSqlite : +deleteByField() dynamic
TaskMappingSqlite : +isValidField() bool
SnapshotRepository <|-- TaskMappingSqlite

class TaskRelationSqlite
TaskRelationSqlite : +db Database
TaskRelationSqlite o-- Database
TaskRelationSqlite : -_table$ String
TaskRelationSqlite : +validFields List~String~
TaskRelationSqlite : +saveSnapshot() dynamic
TaskRelationSqlite : +queryByUuid() dynamic
TaskRelationSqlite : +queryByField() dynamic
TaskRelationSqlite : +loadRelationsForTask() dynamic
TaskRelationSqlite : +deleteRelation() dynamic
TaskRelationSqlite : +deleteByField() dynamic
SnapshotRepository <|-- TaskRelationSqlite

class RepositoryFactory
RepositoryFactory : -_database Database
RepositoryFactory o-- Database
RepositoryFactory : +createTaskRepository() TaskSqlite
RepositoryFactory : +createTimerUnitRepository() TimerUnitSqlite
RepositoryFactory : +createSettingsRepository() SettingsSqlite
RepositoryFactory : +createTaskMappingRepository() TaskMappingSqlite
RepositoryFactory : +createTaskMetaRepository() TaskMetaSqlite
RepositoryFactory : +createTaskRelationRepository() TaskRelationSqlite
RepositoryFactory : +createHistoryRepository() HistorySqlite

class HistorySqlite
HistorySqlite : +db Database
HistorySqlite o-- Database
HistorySqlite : -_table$ String
HistorySqlite : +validFields List~String~
HistorySqlite : +saveSnapshot() dynamic
HistorySqlite : +queryByUuid() dynamic
HistorySqlite : +queryByField() dynamic
HistorySqlite : +deleteByField() dynamic
SnapshotRepository <|-- HistorySqlite

class AppDatabase
AppDatabase : +defaultDbName$ String
AppDatabase : -_db Database
AppDatabase o-- Database
AppDatabase : -_initialized bool
AppDatabase : +db Database
AppDatabase o-- Database
AppDatabase : +init() dynamic
AppDatabase : +upgradeSchema() dynamic
AppDatabase : +setupSchema() dynamic
AppDatabase : +checkInitialized() dynamic

class SettingsSnapshot
SettingsSnapshot : +language String?
SettingsSnapshot : +enableDarkMode bool?
SettingsSnapshot : +autoDarkMode bool?
SettingsSnapshot : +darkModeFollowSystem bool?
SettingsSnapshot : +themeColor String?
SettingsSnapshot : +enableSound bool?
SettingsSnapshot : +enableFinishedSound bool?
SettingsSnapshot : +enableNotification bool?
SettingsSnapshot : +enableDebug bool?
SettingsSnapshot : +enableLog bool?
SettingsSnapshot : +defaultTaskType TaskType?
SettingsSnapshot o-- TaskType
SettingsSnapshot : +defaultTimerUnitType TimerUnitType?
SettingsSnapshot o-- TimerUnitType
SettingsSnapshot : +countdownDuration Duration?
SettingsSnapshot : +taskBatchSize int?
SettingsSnapshot : +historyBatchSize int?
SettingsSnapshot : +toMap() Map<String, dynamic>
SettingsSnapshot : +mergeWith() SettingsSnapshot
SettingsSnapshot : +fromMap()$ SettingsSnapshot
SettingsSnapshot : -_boolFromInt()$ bool?
SnapshotBase <|-- SettingsSnapshot

class TaskRelationSnapshot
TaskRelationSnapshot : +fromUuid String
TaskRelationSnapshot : +toUuid String
TaskRelationSnapshot : +weight double?
TaskRelationSnapshot : +isManuallyLinked bool
TaskRelationSnapshot : +description String?
TaskRelationSnapshot : +toMap() Map<String, dynamic>
TaskRelationSnapshot : +fromMap()$ TaskRelationSnapshot
SnapshotBase <|-- TaskRelationSnapshot

class TaskMetaSnapshot
TaskMetaSnapshot : +taskUuid String
TaskMetaSnapshot : +createdAt DateTime
TaskMetaSnapshot : +firstUsedAt DateTime?
TaskMetaSnapshot : +lastUsedAt DateTime?
TaskMetaSnapshot : +totalUsedCount int
TaskMetaSnapshot : +totalCount int?
TaskMetaSnapshot : +avgSessionDuration Duration?
TaskMetaSnapshot : +icon String?
TaskMetaSnapshot : +baseColor String?
TaskMetaSnapshot : +toMap() Map<String, dynamic>
TaskMetaSnapshot : +fromMap()$ TaskMetaSnapshot
SnapshotBase <|-- TaskMetaSnapshot

class TaskMappingSnapshot
TaskMappingSnapshot : +taskUuid String
TaskMappingSnapshot : +entityUuid String
TaskMappingSnapshot : +entityType String
TaskMappingSnapshot : +toMap() Map<String, dynamic>
TaskMappingSnapshot : +fromMap()$ TaskMappingSnapshot
SnapshotBase <|-- TaskMappingSnapshot

class TaskSnapshot
TaskSnapshot : +uuid String
TaskSnapshot : +name String?
TaskSnapshot : +type TaskType
TaskSnapshot o-- TaskType
TaskSnapshot : +createdAt DateTime
TaskSnapshot : +lastUsedAt DateTime?
TaskSnapshot : +isArchived bool
TaskSnapshot : +isHighlighted bool
TaskSnapshot : +color String?
TaskSnapshot : +opacity double
TaskSnapshot : +orderIndex int
TaskSnapshot : +toMap() Map<String, dynamic>
TaskSnapshot : +fromMap()$ TaskSnapshot
SnapshotBase <|-- TaskSnapshot

class HistorySnapshot
HistorySnapshot : +historyUuid String
HistorySnapshot : +taskUuid String
HistorySnapshot : +startedAt DateTime
HistorySnapshot : +sessionDuration Duration?
HistorySnapshot : +count int?
HistorySnapshot : +isArchived bool
HistorySnapshot : +toMap() Map<String, dynamic>
HistorySnapshot : +fromMap()$ HistorySnapshot
SnapshotBase <|-- HistorySnapshot

class TimerUnitSnapshot
TimerUnitSnapshot : +uuid String
TimerUnitSnapshot : +status TimerUnitStatus
TimerUnitSnapshot o-- TimerUnitStatus
TimerUnitSnapshot : +type TimerUnitType
TimerUnitSnapshot o-- TimerUnitType
TimerUnitSnapshot : +duration Duration
TimerUnitSnapshot : +referenceTime DateTime?
TimerUnitSnapshot : +lastRemainTime Duration?
TimerUnitSnapshot : +toMap() Map<String, dynamic>
TimerUnitSnapshot : +fromMap()$ TimerUnitSnapshot
SnapshotBase <|-- TimerUnitSnapshot

class SnapshotBase
<<abstract>> SnapshotBase
SnapshotBase : +toMap()* Map<String, dynamic>

class MyApp
MyApp : +build() Widget
StatelessWidget <|-- MyApp

class MyHomePage
MyHomePage : +title String
MyHomePage : +createState() State<MyHomePage>
StatefulWidget <|-- MyHomePage

class _MyHomePageState
_MyHomePageState : -_counter int
_MyHomePageState : -_incrementCounter() void
_MyHomePageState : +build() Widget
State <|-- _MyHomePageState

class TimerStatus
<<enumeration>> TimerStatus
TimerStatus : +index int
TimerStatus : +values$ List~TimerStatus~
TimerStatus : +inactive$ TimerStatus
TimerStatus o-- TimerStatus
TimerStatus : +active$ TimerStatus
TimerStatus o-- TimerStatus
TimerStatus : +paused$ TimerStatus
TimerStatus o-- TimerStatus
Enum <|.. TimerStatus

class TimerType
<<enumeration>> TimerType
TimerType : +index int
TimerType : +values$ List~TimerType~
TimerType : +forward$ TimerType
TimerType o-- TimerType
TimerType : +countdown$ TimerType
TimerType o-- TimerType
Enum <|.. TimerType

class DatabaseTables
<<abstract>> DatabaseTables
DatabaseTables : +timerUnits$ TimerUnitsTable
DatabaseTables o-- TimerUnitsTable
DatabaseTables : +history$ HistoryTable
DatabaseTables o-- HistoryTable
DatabaseTables : +tasks$ TasksTable
DatabaseTables o-- TasksTable
DatabaseTables : +taskMeta$ TaskMetaTable
DatabaseTables o-- TaskMetaTable
DatabaseTables : +taskMapping$ TaskMappingTable
DatabaseTables o-- TaskMappingTable
DatabaseTables : +taskRelation$ TaskRelationTable
DatabaseTables o-- TaskRelationTable
DatabaseTables : +settings$ SettingsTable
DatabaseTables o-- SettingsTable

class TimerUnitsTable
TimerUnitsTable : +name String
TimerUnitsTable : +uuid TimerUnitsFields
TimerUnitsTable o-- TimerUnitsFields
TimerUnitsTable : +status TimerUnitsFields
TimerUnitsTable o-- TimerUnitsFields
TimerUnitsTable : +type TimerUnitsFields
TimerUnitsTable o-- TimerUnitsFields
TimerUnitsTable : +durationMs TimerUnitsFields
TimerUnitsTable o-- TimerUnitsFields
TimerUnitsTable : +referenceTime TimerUnitsFields
TimerUnitsTable o-- TimerUnitsFields
TimerUnitsTable : +lastRemainMs TimerUnitsFields
TimerUnitsTable o-- TimerUnitsFields

class HistoryTable
HistoryTable : +name String
HistoryTable : +historyUuid HistoryFields
HistoryTable o-- HistoryFields
HistoryTable : +taskUuid HistoryFields
HistoryTable o-- HistoryFields
HistoryTable : +startedAt HistoryFields
HistoryTable o-- HistoryFields
HistoryTable : +sessionDurationMs HistoryFields
HistoryTable o-- HistoryFields
HistoryTable : +count HistoryFields
HistoryTable o-- HistoryFields
HistoryTable : +isArchived HistoryFields
HistoryTable o-- HistoryFields

class TasksTable
TasksTable : +name String
TasksTable : +uuid TasksFields
TasksTable o-- TasksFields
TasksTable : +nameField TasksFields
TasksTable o-- TasksFields
TasksTable : +type TasksFields
TasksTable o-- TasksFields
TasksTable : +createdAt TasksFields
TasksTable o-- TasksFields
TasksTable : +lastUsedAt TasksFields
TasksTable o-- TasksFields
TasksTable : +isArchived TasksFields
TasksTable o-- TasksFields
TasksTable : +isHighlighted TasksFields
TasksTable o-- TasksFields
TasksTable : +color TasksFields
TasksTable o-- TasksFields
TasksTable : +opacity TasksFields
TasksTable o-- TasksFields
TasksTable : +orderIndex TasksFields
TasksTable o-- TasksFields

class TaskMetaTable
TaskMetaTable : +name String
TaskMetaTable : +taskUuid TaskMetaFields
TaskMetaTable o-- TaskMetaFields
TaskMetaTable : +createdAt TaskMetaFields
TaskMetaTable o-- TaskMetaFields
TaskMetaTable : +firstUsedAt TaskMetaFields
TaskMetaTable o-- TaskMetaFields
TaskMetaTable : +lastUsedAt TaskMetaFields
TaskMetaTable o-- TaskMetaFields
TaskMetaTable : +totalUsedCount TaskMetaFields
TaskMetaTable o-- TaskMetaFields
TaskMetaTable : +totalCount TaskMetaFields
TaskMetaTable o-- TaskMetaFields
TaskMetaTable : +avgSessionDurationMs TaskMetaFields
TaskMetaTable o-- TaskMetaFields
TaskMetaTable : +icon TaskMetaFields
TaskMetaTable o-- TaskMetaFields
TaskMetaTable : +baseColor TaskMetaFields
TaskMetaTable o-- TaskMetaFields

class TaskMappingTable
TaskMappingTable : +name String
TaskMappingTable : +taskUuid TaskMappingFields
TaskMappingTable o-- TaskMappingFields
TaskMappingTable : +entityUuid TaskMappingFields
TaskMappingTable o-- TaskMappingFields
TaskMappingTable : +entityType TaskMappingFields
TaskMappingTable o-- TaskMappingFields

class TaskRelationTable
TaskRelationTable : +name String
TaskRelationTable : +fromUuid TaskRelationFields
TaskRelationTable o-- TaskRelationFields
TaskRelationTable : +toUuid TaskRelationFields
TaskRelationTable o-- TaskRelationFields
TaskRelationTable : +weight TaskRelationFields
TaskRelationTable o-- TaskRelationFields
TaskRelationTable : +isManuallyLinked TaskRelationFields
TaskRelationTable o-- TaskRelationFields
TaskRelationTable : +description TaskRelationFields
TaskRelationTable o-- TaskRelationFields

class SettingsTable
SettingsTable : +name String
SettingsTable : +id SettingsFields
SettingsTable o-- SettingsFields
SettingsTable : +json SettingsFields
SettingsTable o-- SettingsFields

class QueryRelation
<<enumeration>> QueryRelation
QueryRelation : +index int
QueryRelation : +values$ List~QueryRelation~
QueryRelation : +equal$ QueryRelation
QueryRelation o-- QueryRelation
QueryRelation : +notEqual$ QueryRelation
QueryRelation o-- QueryRelation
QueryRelation : +lessThan$ QueryRelation
QueryRelation o-- QueryRelation
QueryRelation : +lessEqual$ QueryRelation
QueryRelation o-- QueryRelation
QueryRelation : +greaterThan$ QueryRelation
QueryRelation o-- QueryRelation
QueryRelation : +greaterEqual$ QueryRelation
QueryRelation o-- QueryRelation
QueryRelation : +like$ QueryRelation
QueryRelation o-- QueryRelation
QueryRelation : +any$ QueryRelation
QueryRelation o-- QueryRelation
Enum <|.. QueryRelation

class TimerUnitsFields
<<enumeration>> TimerUnitsFields
TimerUnitsFields : +index int
TimerUnitsFields : +values$ List~TimerUnitsFields~
TimerUnitsFields : +uuid$ TimerUnitsFields
TimerUnitsFields o-- TimerUnitsFields
TimerUnitsFields : +status$ TimerUnitsFields
TimerUnitsFields o-- TimerUnitsFields
TimerUnitsFields : +type$ TimerUnitsFields
TimerUnitsFields o-- TimerUnitsFields
TimerUnitsFields : +durationMs$ TimerUnitsFields
TimerUnitsFields o-- TimerUnitsFields
TimerUnitsFields : +referenceTime$ TimerUnitsFields
TimerUnitsFields o-- TimerUnitsFields
TimerUnitsFields : +lastRemainMs$ TimerUnitsFields
TimerUnitsFields o-- TimerUnitsFields
Enum <|.. TimerUnitsFields

class HistoryFields
<<enumeration>> HistoryFields
HistoryFields : +index int
HistoryFields : +values$ List~HistoryFields~
HistoryFields : +historyUuid$ HistoryFields
HistoryFields o-- HistoryFields
HistoryFields : +taskUuid$ HistoryFields
HistoryFields o-- HistoryFields
HistoryFields : +startedAt$ HistoryFields
HistoryFields o-- HistoryFields
HistoryFields : +sessionDurationMs$ HistoryFields
HistoryFields o-- HistoryFields
HistoryFields : +count$ HistoryFields
HistoryFields o-- HistoryFields
HistoryFields : +isArchived$ HistoryFields
HistoryFields o-- HistoryFields
Enum <|.. HistoryFields

class TasksFields
<<enumeration>> TasksFields
TasksFields : +index int
TasksFields : +values$ List~TasksFields~
TasksFields : +uuid$ TasksFields
TasksFields o-- TasksFields
TasksFields : +nameField$ TasksFields
TasksFields o-- TasksFields
TasksFields : +type$ TasksFields
TasksFields o-- TasksFields
TasksFields : +createdAt$ TasksFields
TasksFields o-- TasksFields
TasksFields : +lastUsedAt$ TasksFields
TasksFields o-- TasksFields
TasksFields : +isArchived$ TasksFields
TasksFields o-- TasksFields
TasksFields : +isHighlighted$ TasksFields
TasksFields o-- TasksFields
TasksFields : +color$ TasksFields
TasksFields o-- TasksFields
TasksFields : +opacity$ TasksFields
TasksFields o-- TasksFields
TasksFields : +orderIndex$ TasksFields
TasksFields o-- TasksFields
Enum <|.. TasksFields

class TaskMetaFields
<<enumeration>> TaskMetaFields
TaskMetaFields : +index int
TaskMetaFields : +values$ List~TaskMetaFields~
TaskMetaFields : +taskUuid$ TaskMetaFields
TaskMetaFields o-- TaskMetaFields
TaskMetaFields : +createdAt$ TaskMetaFields
TaskMetaFields o-- TaskMetaFields
TaskMetaFields : +firstUsedAt$ TaskMetaFields
TaskMetaFields o-- TaskMetaFields
TaskMetaFields : +lastUsedAt$ TaskMetaFields
TaskMetaFields o-- TaskMetaFields
TaskMetaFields : +totalUsedCount$ TaskMetaFields
TaskMetaFields o-- TaskMetaFields
TaskMetaFields : +totalCount$ TaskMetaFields
TaskMetaFields o-- TaskMetaFields
TaskMetaFields : +avgSessionDurationMs$ TaskMetaFields
TaskMetaFields o-- TaskMetaFields
TaskMetaFields : +icon$ TaskMetaFields
TaskMetaFields o-- TaskMetaFields
TaskMetaFields : +baseColor$ TaskMetaFields
TaskMetaFields o-- TaskMetaFields
Enum <|.. TaskMetaFields

class TaskMappingFields
<<enumeration>> TaskMappingFields
TaskMappingFields : +index int
TaskMappingFields : +values$ List~TaskMappingFields~
TaskMappingFields : +taskUuid$ TaskMappingFields
TaskMappingFields o-- TaskMappingFields
TaskMappingFields : +entityUuid$ TaskMappingFields
TaskMappingFields o-- TaskMappingFields
TaskMappingFields : +entityType$ TaskMappingFields
TaskMappingFields o-- TaskMappingFields
Enum <|.. TaskMappingFields

class TaskRelationFields
<<enumeration>> TaskRelationFields
TaskRelationFields : +index int
TaskRelationFields : +values$ List~TaskRelationFields~
TaskRelationFields : +fromUuid$ TaskRelationFields
TaskRelationFields o-- TaskRelationFields
TaskRelationFields : +toUuid$ TaskRelationFields
TaskRelationFields o-- TaskRelationFields
TaskRelationFields : +weight$ TaskRelationFields
TaskRelationFields o-- TaskRelationFields
TaskRelationFields : +isManuallyLinked$ TaskRelationFields
TaskRelationFields o-- TaskRelationFields
TaskRelationFields : +description$ TaskRelationFields
TaskRelationFields o-- TaskRelationFields
Enum <|.. TaskRelationFields

class SettingsFields
<<enumeration>> SettingsFields
SettingsFields : +index int
SettingsFields : +values$ List~SettingsFields~
SettingsFields : +id$ SettingsFields
SettingsFields o-- SettingsFields
SettingsFields : +json$ SettingsFields
SettingsFields o-- SettingsFields
Enum <|.. SettingsFields

class TimerUnitType
<<enumeration>> TimerUnitType
TimerUnitType : +index int
TimerUnitType : +values$ List~TimerUnitType~
TimerUnitType : +countup$ TimerUnitType
TimerUnitType o-- TimerUnitType
TimerUnitType : +countdown$ TimerUnitType
TimerUnitType o-- TimerUnitType
Enum <|.. TimerUnitType

class TaskType
<<enumeration>> TaskType
TaskType : +index int
TaskType : +values$ List~TaskType~
TaskType : +timer$ TaskType
TaskType o-- TaskType
TaskType : +note$ TaskType
TaskType o-- TaskType
Enum <|.. TaskType

class TimerUnitStatus
<<enumeration>> TimerUnitStatus
TimerUnitStatus : +index int
TimerUnitStatus : +values$ List~TimerUnitStatus~
TimerUnitStatus : +active$ TimerUnitStatus
TimerUnitStatus o-- TimerUnitStatus
TimerUnitStatus : +inactive$ TimerUnitStatus
TimerUnitStatus o-- TimerUnitStatus
TimerUnitStatus : +paused$ TimerUnitStatus
TimerUnitStatus o-- TimerUnitStatus
TimerUnitStatus : +timeout$ TimerUnitStatus
TimerUnitStatus o-- TimerUnitStatus
Enum <|.. TimerUnitStatus

class DefaultSettings
DefaultSettings : +language$ String
DefaultSettings : +enableDarkMode$ bool
DefaultSettings : +autoDarkMode$ bool
DefaultSettings : +darkModeFollowSystem$ bool
DefaultSettings : +themeColor$ String
DefaultSettings : +enableSound$ bool
DefaultSettings : +enableFinishedSound$ bool
DefaultSettings : +enableNotification$ bool
DefaultSettings : +enableDebug$ bool
DefaultSettings : +enableLog$ bool
DefaultSettings : +defaultTaskType$ TaskType
DefaultSettings o-- TaskType
DefaultSettings : +defaultTimerUnitType$ TimerUnitType
DefaultSettings o-- TimerUnitType
DefaultSettings : +countdownDuration$ Duration
DefaultSettings : +taskBatchSize$ int
DefaultSettings : +historyBatchSize$ int
DefaultSettings : +toSnapshot()$ SettingsSnapshot
DefaultSettings : +toMap()$ Map<String, dynamic>

class Clock
Clock : -_instance$ Clock
Clock o-- Clock
Clock : -_timeDrift int
Clock : -_timezoneOffset int
Clock : +instance$ dynamic
Clock : +currentTime DateTime
Clock : +setTimeDrift int
Clock : +setTimezoneOffset int
Clock : +reset() void

class UuidHelper
UuidHelper : +getUuid()$ String

class Settings
Settings : -_language String?
Settings : -_enableDarkMode bool?
Settings : -_autoDarkMode bool?
Settings : -_darkModeFollowSystem bool?
Settings : -_themeColor String?
Settings : -_enableSound bool?
Settings : -_enableFinishedSound bool?
Settings : -_enableNotification bool?
Settings : -_enableDebug bool?
Settings : -_enableLog bool?
Settings : -_defaultTaskType TaskType?
Settings o-- TaskType
Settings : -_defaultTimerUnitType TimerUnitType?
Settings o-- TimerUnitType
Settings : -_countdownDuration Duration?
Settings : -_taskBatchSize int?
Settings : -_historyBatchSize int?
Settings : +language String?
Settings : +enableDarkMode bool?
Settings : +autoDarkMode bool?
Settings : +darkModeFollowSystem bool?
Settings : +themeColor String?
Settings : +enableSound bool?
Settings : +enableFinishedSound bool?
Settings : +enableNotification bool?
Settings : +enableDebug bool?
Settings : +enableLog bool?
Settings : +defaultTaskType TaskType?
Settings o-- TaskType
Settings : +defaultTimerUnitType TimerUnitType?
Settings o-- TimerUnitType
Settings : +countdownDuration Duration?
Settings : +taskBatchSize int?
Settings : +historyBatchSize int?
Settings : +toSnapshot() SettingsSnapshot
Settings : +fromSnapshot() void

class DatabaseInitService
DatabaseInitService : +initDatabaseEnvironment()$ void
DatabaseInitService : +initializeAppDatabase()$ dynamic

class AppStartupService
AppStartupService : -_database AppDatabase
AppStartupService o-- AppDatabase
AppStartupService : -_repositoryFactory RepositoryFactory
AppStartupService o-- RepositoryFactory
AppStartupService : -_taskRepo TaskSqlite
AppStartupService o-- TaskSqlite
AppStartupService : -_timerRepo TimerUnitSqlite
AppStartupService o-- TimerUnitSqlite
AppStartupService : -_settingsRepo SettingsSqlite
AppStartupService o-- SettingsSqlite
AppStartupService : -_taskMappingRepo TaskMappingSqlite
AppStartupService o-- TaskMappingSqlite
AppStartupService : -_taskMetaRepo TaskMetaSqlite
AppStartupService o-- TaskMetaSqlite
AppStartupService : -_taskRelationRepo TaskRelationSqlite
AppStartupService o-- TaskRelationSqlite
AppStartupService : -_historyRepo HistorySqlite
AppStartupService o-- HistorySqlite
AppStartupService : +timerRepo TimerUnitSqlite
AppStartupService o-- TimerUnitSqlite
AppStartupService : +settingsRepo SettingsSqlite
AppStartupService o-- SettingsSqlite
AppStartupService : +taskRepo TaskSqlite
AppStartupService o-- TaskSqlite
AppStartupService : +taskMappingRepo TaskMappingSqlite
AppStartupService o-- TaskMappingSqlite
AppStartupService : +taskMetaRepo TaskMetaSqlite
AppStartupService o-- TaskMetaSqlite
AppStartupService : +taskRelationRepo TaskRelationSqlite
AppStartupService o-- TaskRelationSqlite
AppStartupService : +historyRepo HistorySqlite
AppStartupService o-- HistorySqlite
AppStartupService : +initializeApp() dynamic
AppStartupService : -_recoverUnfinishedTimers() dynamic
AppStartupService : -_cleanupExtraTimers() dynamic

class TaskService

class SettingsController
SettingsController : -_repo SettingsSqlite
SettingsController o-- SettingsSqlite
SettingsController : +build() dynamic
SettingsController : +load() dynamic
SettingsController : +save() dynamic
SettingsController : +setLanguage() dynamic
SettingsController : +setEnableDarkMode() dynamic
SettingsController : +setAutoDarkMode() dynamic
SettingsController : +setDarkModeFollowSystem() dynamic
SettingsController : +setThemeColor() dynamic
SettingsController : +setEnableSound() dynamic
SettingsController : +setEnableFinishedSound() dynamic
SettingsController : +setEnableNotification() dynamic
SettingsController : +setEnableDebug() dynamic
SettingsController : +setEnableLog() dynamic
SettingsController : +setDefaultTaskType() dynamic
SettingsController : +setDefaultTimerUnitType() dynamic
SettingsController : +setCountdownDuration() dynamic
AsyncNotifier <|-- SettingsController

class TaskMappingController
TaskMappingController : -_repo TaskMappingSqlite
TaskMappingController o-- TaskMappingSqlite
TaskMappingController : -_settings Settings
TaskMappingController o-- Settings
TaskMappingController : -_batchSize int
TaskMappingController : +build() dynamic
TaskMappingController : +save() dynamic
TaskMappingController : +addItem() dynamic
TaskMappingController : +removeWhere() dynamic
TaskMappingController : +updateWhere() dynamic
TaskMappingController : +loadMappingsForTask() dynamic
TaskMappingController : +loadMappingsForEntity() dynamic
TaskMappingController : +addMapping() dynamic
TaskMappingController : +deleteMapping() dynamic
CollectionController <|-- TaskMappingController

class TaskController
TaskController : -_repo TaskSqlite
TaskController o-- TaskSqlite
TaskController : -_settings Settings
TaskController o-- Settings
TaskController : -_batchSize int
TaskController : -_orderIndexAllocator OrderIndexAllocator
TaskController o-- OrderIndexAllocator
TaskController : +build() dynamic
TaskController : +load() dynamic
TaskController : +save() dynamic
TaskController : +addItem() dynamic
TaskController : +removeWhere() dynamic
TaskController : +updateWhere() dynamic
CollectionController <|-- TaskController

class OrderIndexAllocator
OrderIndexAllocator : -_repo TaskSqlite
OrderIndexAllocator o-- TaskSqlite
OrderIndexAllocator : +shouldReorder() bool
OrderIndexAllocator : +allocateOrderAtEnd() dynamic
OrderIndexAllocator : +allocateOrderBetween() dynamic
OrderIndexAllocator : +reorderAround() dynamic
OrderIndexAllocator : +getLowerNeighborOrderByUuid() dynamic
OrderIndexAllocator : +getUpperNeighborOrderByUuid() dynamic
OrderIndexAllocator : +Future() dynamic
OrderIndexAllocator : +() dynamic
OrderIndexAllocator : +?() dynamic
OrderIndexAllocator : +>() dynamic
OrderIndexAllocator : +getNeighborOrderByUuid() dynamic

class CollectionController
<<abstract>> CollectionController
CollectionController : +addItem()* dynamic
CollectionController : +removeWhere()* dynamic
CollectionController : +updateWhere()* dynamic
BaseController <|-- CollectionController

class BaseController
<<abstract>> BaseController
BaseController : +save()* dynamic
BaseController : +handleError() void
AsyncNotifier <|-- BaseController

class TimerController
TimerController : -_repo TimerUnitSqlite
TimerController o-- TimerUnitSqlite
TimerController : -_settings Settings
TimerController o-- Settings
TimerController : +build() dynamic
TimerController : +save() dynamic
TimerController : +loadFromUuid() dynamic
TimerController : +create() dynamic
TimerController : +start() dynamic
TimerController : +stop() dynamic
TimerController : +pause() dynamic
TimerController : +resume() dynamic
TimerController : +reset() dynamic
TimerController : +switchType() dynamic
TimerController : +setCountdownDuration() dynamic
TimerController : +applySettings() dynamic
BaseController <|-- TimerController

class RepositoryProviderFactory
RepositoryProviderFactory : +createRepositoryProvider()$ FutureProvider<T>

class Task
Task : -_uuid String
Task : -_name String?
Task : -_type TaskType
Task o-- TaskType
Task : -_createdAt DateTime
Task : -_lastUsedAt DateTime?
Task : -_isArchived bool
Task : -_isHighlighted bool
Task : -_color String?
Task : -_opacity double
Task : -_orderIndex int
Task : +name String?
Task : +type TaskType
Task o-- TaskType
Task : +isArchived bool
Task : +isHighlighted bool
Task : +color String?
Task : +opacity double
Task : +orderIndex int
Task : +uuid String
Task : +createdAt DateTime
Task : +lastUsedAt DateTime?
Task : +toSnapshot() TaskSnapshot
Task : +fromSnapshot() void

class TaskMapping
TaskMapping : -_taskUuid String
TaskMapping : -_entityUuid String
TaskMapping : -_entityType String
TaskMapping : +taskUuid String
TaskMapping : +entityUuid String
TaskMapping : +entityType String
TaskMapping : +toSnapshot() TaskMappingSnapshot

class TaskMeta
TaskMeta : -_taskUuid String
TaskMeta : -_createdAt DateTime
TaskMeta : -_firstUsedAt DateTime?
TaskMeta : -_lastUsedAt DateTime?
TaskMeta : -_totalUsedCount int
TaskMeta : -_totalCount int?
TaskMeta : -_avgSessionDuration Duration?
TaskMeta : -_icon String?
TaskMeta : -_baseColor String?
TaskMeta : +setFirstUsedAt DateTime
TaskMeta : +setLastUsedAt DateTime
TaskMeta : +setIcon String
TaskMeta : +setBaseColor String
TaskMeta : +toSnapshot() TaskMetaSnapshot
TaskMeta : +fromSnapshot() void

class TaskRelation
TaskRelation : -_fromUuid String
TaskRelation : -_toUuid String
TaskRelation : -_weight double?
TaskRelation : -_isManuallyLinked bool
TaskRelation : -_description String?
TaskRelation : +fromUuid String
TaskRelation : +toUuid String
TaskRelation : +weight double?
TaskRelation : +isManuallyLinked bool
TaskRelation : +description String?
TaskRelation : +toSnapshot() TaskRelationSnapshot

class History
History : -_historyUuid String
History : -_taskUuid String
History : -_startedAt DateTime
History : -_sessionDuration Duration?
History : -_count int?
History : -_isArchived bool
History : +setSessionDuration Duration
History : +historyUuid String
History : +taskUuid String
History : +startedAt DateTime
History : +sessionDuration Duration?
History : +count int?
History : +isArchived bool
History : +addToCount() void
History : +toSnapshot() HistorySnapshot
History : +fromSnapshot() void

class TimerUnit
TimerUnit : -_uuid String
TimerUnit : -_status TimerUnitStatus
TimerUnit o-- TimerUnitStatus
TimerUnit : -_timerUnitType TimerUnitType
TimerUnit o-- TimerUnitType
TimerUnit : -_currentTimer TimerBase
TimerUnit o-- TimerBase
TimerUnit : -_duration Duration
TimerUnit : -_referenceTime DateTime?
TimerUnit : -_lastRemainTime Duration?
TimerUnit : +uuid String
TimerUnit : +status TimerUnitStatus
TimerUnit o-- TimerUnitStatus
TimerUnit : +type TimerUnitType
TimerUnit o-- TimerUnitType
TimerUnit : +duration Duration
TimerUnit : +toCountup() void
TimerUnit : +toCountdown() void
TimerUnit : +reset() void
TimerUnit : +start() void
TimerUnit : +pause() void
TimerUnit : +resume() void
TimerUnit : +stop() void
TimerUnit : -_update() void
TimerUnit : -_checkTimeout() void
TimerUnit : -_reset() void
TimerUnit : +toSnapshot() TimerUnitSnapshot
TimerUnit : +fromSnapshot() void

class TimerBase
<<abstract>> TimerBase
TimerBase : +isCountup bool
TimerBase : +isCountdown bool
TimerBase : +duration()* Duration
TimerBase : +referenceTime()* DateTime
TimerBase : +start()* void
TimerBase : +stop()* void

class CountupTimer
CountupTimer : -_totalDuration Duration
CountupTimer : -_startTime DateTime?
CountupTimer : +isCountup bool
CountupTimer : +isCountdown bool
CountupTimer : +totalDuration Duration
CountupTimer : +startTime DateTime
CountupTimer : +duration() Duration
CountupTimer : +referenceTime() DateTime
CountupTimer : +start() void
CountupTimer : +stop() void
CountupTimer : +reset() void
TimerBase <|-- CountupTimer

class CountdownTimer
CountdownTimer : -_remainDuration Duration
CountdownTimer : -_endTime DateTime?
CountdownTimer : +isCountup bool
CountdownTimer : +isCountdown bool
CountdownTimer : +remainDuration Duration
CountdownTimer : +endTime DateTime
CountdownTimer : +duration() Duration
CountdownTimer : +referenceTime() DateTime
CountdownTimer : +start() void
CountdownTimer : +stop() void
CountdownTimer : +reset() void
TimerBase <|-- CountdownTimer

