classDiagram

class SnapshotBase
<<abstract>> SnapshotBase
SnapshotBase : +toMap()* Map<String, dynamic>

class TimerUnitSnapshot
TimerUnitSnapshot : +uuid String
TimerUnitSnapshot : +status TimerUnitStatus
TimerUnitSnapshot o-- TimerUnitStatus
TimerUnitSnapshot : +type TimerUnitType
TimerUnitSnapshot o-- TimerUnitType
TimerUnitSnapshot : +duration Duration
TimerUnitSnapshot : +referenceTime DateTime?
TimerUnitSnapshot : +lastRemainTime Duration?
TimerUnitSnapshot : +toMap() Map<String, dynamic>
TimerUnitSnapshot : +fromMap()$ TimerUnitSnapshot
SnapshotBase <|-- TimerUnitSnapshot

class UserSettingsSnapshot
UserSettingsSnapshot : +language String?
UserSettingsSnapshot : +enableDarkMode bool?
UserSettingsSnapshot : +autoDarkMode bool?
UserSettingsSnapshot : +darkModeFollowSystem bool?
UserSettingsSnapshot : +themeColor String?
UserSettingsSnapshot : +enableSound bool?
UserSettingsSnapshot : +enableFinishedSound bool?
UserSettingsSnapshot : +enableNotification bool?
UserSettingsSnapshot : +enableDebug bool?
UserSettingsSnapshot : +enableLog bool?
UserSettingsSnapshot : +defaultTaskType TaskType?
UserSettingsSnapshot o-- TaskType
UserSettingsSnapshot : +defaultTimerUnitType TimerUnitType?
UserSettingsSnapshot o-- TimerUnitType
UserSettingsSnapshot : +countdownDuration Duration?
UserSettingsSnapshot : +toMap() Map<String, dynamic>
UserSettingsSnapshot : +mergeWith() UserSettingsSnapshot
UserSettingsSnapshot : +fromMap()$ UserSettingsSnapshot
UserSettingsSnapshot : -_boolFromInt()$ bool?
SnapshotBase <|-- UserSettingsSnapshot

class TaskMetaSnapshot
TaskMetaSnapshot : +uuid String
TaskMetaSnapshot : +name String
TaskMetaSnapshot : +type String
TaskMetaSnapshot : +createAt DateTime
TaskMetaSnapshot : +description String?
TaskMetaSnapshot : +archived bool
TaskMetaSnapshot : +toMap() Map<String, dynamic>
TaskMetaSnapshot : +fromMap()$ TaskMetaSnapshot
SnapshotBase <|-- TaskMetaSnapshot

class TaskType
<<enumeration>> TaskType
TaskType : +index int
TaskType : +values$ List~TaskType~
TaskType : +timer$ TaskType
TaskType o-- TaskType
TaskType : +note$ TaskType
TaskType o-- TaskType
Enum <|.. TaskType

class TimerType
<<enumeration>> TimerType
TimerType : +index int
TimerType : +values$ List~TimerType~
TimerType : +forward$ TimerType
TimerType o-- TimerType
TimerType : +countdown$ TimerType
TimerType o-- TimerType
Enum <|.. TimerType

class DefaultSettings
DefaultSettings : +language$ String
DefaultSettings : +enableDarkMode$ bool
DefaultSettings : +autoDarkMode$ bool
DefaultSettings : +darkModeFollowSystem$ bool
DefaultSettings : +themeColor$ String
DefaultSettings : +enableSound$ bool
DefaultSettings : +enableFinishedSound$ bool
DefaultSettings : +enableNotification$ bool
DefaultSettings : +enableDebug$ bool
DefaultSettings : +enableLog$ bool
DefaultSettings : +defaultTaskType$ TaskType
DefaultSettings o-- TaskType
DefaultSettings : +defaultTimerUnitType$ TimerUnitType
DefaultSettings o-- TimerUnitType
DefaultSettings : +countdownDuration$ Duration
DefaultSettings : +toSnapshot()$ UserSettingsSnapshot

class TimerUnitStatus
<<enumeration>> TimerUnitStatus
TimerUnitStatus : +index int
TimerUnitStatus : +values$ List~TimerUnitStatus~
TimerUnitStatus : +active$ TimerUnitStatus
TimerUnitStatus o-- TimerUnitStatus
TimerUnitStatus : +inactive$ TimerUnitStatus
TimerUnitStatus o-- TimerUnitStatus
TimerUnitStatus : +paused$ TimerUnitStatus
TimerUnitStatus o-- TimerUnitStatus
TimerUnitStatus : +timeout$ TimerUnitStatus
TimerUnitStatus o-- TimerUnitStatus
Enum <|.. TimerUnitStatus

class TimerStatus
<<enumeration>> TimerStatus
TimerStatus : +index int
TimerStatus : +values$ List~TimerStatus~
TimerStatus : +inactive$ TimerStatus
TimerStatus o-- TimerStatus
TimerStatus : +active$ TimerStatus
TimerStatus o-- TimerStatus
TimerStatus : +paused$ TimerStatus
TimerStatus o-- TimerStatus
Enum <|.. TimerStatus

class TimerUnitType
<<enumeration>> TimerUnitType
TimerUnitType : +index int
TimerUnitType : +values$ List~TimerUnitType~
TimerUnitType : +countup$ TimerUnitType
TimerUnitType o-- TimerUnitType
TimerUnitType : +countdown$ TimerUnitType
TimerUnitType o-- TimerUnitType
Enum <|.. TimerUnitType

class Clock
Clock : -_instance$ Clock
Clock o-- Clock
Clock : -_timeDrift int
Clock : -_timezoneOffset int
Clock : +currentTime DateTime
Clock : +setTimeDrift() void
Clock : +setTimezoneOffset() void
Clock : +reset() void

class UuidHelper
UuidHelper : +getUuid()$ String

class TimerController
TimerController : -_repo TimerUnitSqlite
TimerController o-- TimerUnitSqlite
TimerController : -_settings UserSettings
TimerController o-- UserSettings
TimerController : +build() dynamic
TimerController : +create() dynamic
TimerController : +loadFromUuid() dynamic
TimerController : +save() dynamic
TimerController : +start() dynamic
TimerController : +stop() dynamic
TimerController : +pause() dynamic
TimerController : +resume() dynamic
AsyncNotifier <|-- TimerController

class ConfigController
ConfigController : -_repo UserSettingsSqlite
ConfigController o-- UserSettingsSqlite
ConfigController : +build() dynamic
ConfigController : +load() dynamic
ConfigController : +save() dynamic
AsyncNotifier <|-- ConfigController

class AppStartupService
AppStartupService : -_database AppDatabase
AppStartupService o-- AppDatabase
AppStartupService : -_taskRepo TaskMetaSqlite
AppStartupService o-- TaskMetaSqlite
AppStartupService : -_timerRepo TimerUnitSqlite
AppStartupService o-- TimerUnitSqlite
AppStartupService : -_settingsRepo UserSettingsSqlite
AppStartupService o-- UserSettingsSqlite
AppStartupService : +timerRepo dynamic
AppStartupService : +settingsRepo dynamic
AppStartupService : +initializeApp() dynamic
AppStartupService : -_recoverUnfinishedTimers() dynamic

class UserSettings
UserSettings : -_language String?
UserSettings : -_enableDarkMode bool?
UserSettings : -_autoDarkMode bool?
UserSettings : -_darkModeFollowSystem bool?
UserSettings : -_themeColor String?
UserSettings : -_enableSound bool?
UserSettings : -_enableFinishedSound bool?
UserSettings : -_enableNotification bool?
UserSettings : -_enableDebug bool?
UserSettings : -_enableLog bool?
UserSettings : -_defaultTaskType TaskType?
UserSettings o-- TaskType
UserSettings : -_defaultTimerUnitType TimerUnitType?
UserSettings o-- TimerUnitType
UserSettings : -_countdownDuration Duration?
UserSettings : +language String?
UserSettings : +enableDarkMode bool?
UserSettings : +autoDarkMode bool?
UserSettings : +darkModeFollowSystem bool?
UserSettings : +themeColor String?
UserSettings : +enableSound bool?
UserSettings : +enableFinishedSound bool?
UserSettings : +enableNotification bool?
UserSettings : +enableDebug bool?
UserSettings : +enableLog bool?
UserSettings : +defaultTaskType TaskType?
UserSettings o-- TaskType
UserSettings : +defaultTimerUnitType TimerUnitType?
UserSettings o-- TimerUnitType
UserSettings : +countdownDuration Duration?
UserSettings : +toSnapshot() UserSettingsSnapshot
UserSettings : +fromSnapshot() void

class TimerUnitSqlite
TimerUnitSqlite : +db Database
TimerUnitSqlite o-- Database
TimerUnitSqlite : -_table$ String
TimerUnitSqlite : +saveSnapshot() dynamic
TimerUnitSqlite : +loadSnapshot() dynamic
SnapshotRepository <|.. TimerUnitSqlite

class AppDatabase
AppDatabase : +defaultDbName$ String
AppDatabase : -_db Database
AppDatabase o-- Database
AppDatabase : -_initialized bool
AppDatabase : +db Database
AppDatabase o-- Database
AppDatabase : +init() dynamic
AppDatabase : +setupSchema() dynamic
AppDatabase : +checkInitialized() dynamic
AppDatabase : +setInitializedFlag() dynamic

class TaskMetaSqlite
TaskMetaSqlite : +db Database
TaskMetaSqlite o-- Database
TaskMetaSqlite : -_table$ String
TaskMetaSqlite : +saveSnapshot() dynamic
TaskMetaSqlite : +loadSnapshot() dynamic
SnapshotRepository <|.. TaskMetaSqlite

class UserSettingsSqlite
UserSettingsSqlite : +db Database
UserSettingsSqlite o-- Database
UserSettingsSqlite : -_table$ String
UserSettingsSqlite : +saveSnapshot() dynamic
UserSettingsSqlite : +loadSnapshot() dynamic
SnapshotRepository <|.. UserSettingsSqlite

class SnapshotRepository
<<abstract>> SnapshotRepository
SnapshotRepository : +saveSnapshot()* dynamic
SnapshotRepository : +loadSnapshot()* dynamic

class TimerBase
<<abstract>> TimerBase
TimerBase : +isCountup bool
TimerBase : +isCountdown bool
TimerBase : +duration()* Duration
TimerBase : +referenceTime()* DateTime
TimerBase : +start()* void
TimerBase : +stop()* void

class CountupTimer
CountupTimer : -_totalDuration Duration
CountupTimer : -_startTime DateTime?
CountupTimer : +isCountup bool
CountupTimer : +isCountdown bool
CountupTimer : +totalDuration Duration
CountupTimer : +startTime DateTime
CountupTimer : +duration() Duration
CountupTimer : +referenceTime() DateTime
CountupTimer : +start() void
CountupTimer : +stop() void
CountupTimer : +reset() void
TimerBase <|-- CountupTimer

class CountdownTimer
CountdownTimer : -_remainDuration Duration
CountdownTimer : -_endTime DateTime?
CountdownTimer : +isCountup bool
CountdownTimer : +isCountdown bool
CountdownTimer : +remainDuration Duration
CountdownTimer : +endTime DateTime
CountdownTimer : +duration() Duration
CountdownTimer : +referenceTime() DateTime
CountdownTimer : +start() void
CountdownTimer : +stop() void
CountdownTimer : +reset() void
TimerBase <|-- CountdownTimer

class TimerUnit
TimerUnit : -_uuid String
TimerUnit : -_status TimerUnitStatus
TimerUnit o-- TimerUnitStatus
TimerUnit : -_timerUnitType TimerUnitType
TimerUnit o-- TimerUnitType
TimerUnit : -_currentTimer TimerBase
TimerUnit o-- TimerBase
TimerUnit : -_duration Duration
TimerUnit : -_referenceTime DateTime?
TimerUnit : -_lastRemainTime Duration?
TimerUnit : +clock Clock
TimerUnit o-- Clock
TimerUnit : +uuid String
TimerUnit : +status TimerUnitStatus
TimerUnit o-- TimerUnitStatus
TimerUnit : +type TimerUnitType
TimerUnit o-- TimerUnitType
TimerUnit : +duration Duration
TimerUnit : +toCountup() void
TimerUnit : +toCountdown() void
TimerUnit : +start() void
TimerUnit : +pause() void
TimerUnit : +resume() void
TimerUnit : +stop() void
TimerUnit : -_update() void
TimerUnit : -_checkTimeout() void
TimerUnit : -_reset() void
TimerUnit : +toSnapshot() TimerUnitSnapshot
TimerUnit : +fromSnapshot() void

class TaskMeta
TaskMeta : -_uuid String
TaskMeta : -_name String
TaskMeta : -_type String
TaskMeta : -_createAt DateTime
TaskMeta : -_description String?
TaskMeta : -_archived bool
TaskMeta : +name String
TaskMeta : +type String
TaskMeta : +description String?
TaskMeta : +archived bool
TaskMeta : +toSnapshot() TaskMetaSnapshot
TaskMeta : +fromSnapshot() void

